PDP Academy/lesson03/Controllers/StudentsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using PDP_Academy.DAL;
using PDP_Academy.Models;
using Microsoft.AspNetCore.Mvc.Rendering;
using PDP_Academy.ViewModels;

namespace PDP_Academy.Controllers
{
    public class StudentsController : Controller
    {
        private readonly PdpDbContext _context;

        public StudentsController(PdpDbContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index(string sortOrder)
        {
            ViewData["CurrentSort"] = sortOrder;
            ViewData["FullNameSort"] = sortOrder == "fullName_asc" ? "fullName_desc" : "fullName_asc";
            ViewData["AgeSort"] = sortOrder == "age_asc" ? "age_desc" : "age_asc";

            var students = _context.Students.AsQueryable();

            students = sortOrder switch
            {
                "fullName_asc" => students.OrderBy(x => x.FullName),
                "fullName_desc" => students.OrderByDescending(x => x.FullName),
                "age_asc" => students.OrderBy(x => x.Age),
                "age_desc" => students.OrderByDescending(x => x.Age),
                _ => students.OrderBy(x => x.Id)
            };

            var groups = await _context.Groups.Select(x => new SelectListItem()
            {
                Text = x.Name,
                Value = x.Id.ToString(),
            }).ToListAsync();   

            var studentsViewModel = new StudentViewModel()
            {
                Students = await students.ToListAsync(),
                Groups = groups
            };

            return View(studentsViewModel);
        }

        [HttpPost]
        public async Task<IActionResult> Index(string? searchString, string group)
        {
            if (searchString == null && group == "All")
            {
                var students1 = _context.Students.ToList();

                var groups1 = await _context.Groups.Select(x => new SelectListItem
                {
                    Value = x.Id.ToString(),
                    Text = x.Name
                }).ToListAsync();

                var studentVM1 = new StudentViewModel()
                {
                    Students = students1,
                    Groups = groups1
                };

                return View(studentVM1);
            }
            else if (group == "All")
            {
                var students1 = await _context.Students
                .Include(s => s.Enrollments)
                .ThenInclude(e => e.Group)
                .Where(s => s.FullName.ToLower().Contains(searchString.ToLower()))
                .ToListAsync();

                var groups1 = await _context.Groups.Select(x => new SelectListItem
                {
                    Value = x.Id.ToString(),
                    Text = x.Name
                }).ToListAsync();

                var studentVM1 = new StudentViewModel()
                {
                    Students = students1,
                    Groups = groups1
                };
                return View(studentVM1);
            }
            else if (searchString == null)
            {
                int groupId1 = int.Parse(group);
                var students1 = await _context.Students
                .Include(s => s.Enrollments)
                .ThenInclude(e => e.Group)
                .Where(x => x.Enrollments.Any(e => e.GroupId == groupId1))
                .ToListAsync();

                var groups1 = await _context.Groups.Select(x => new SelectListItem
                {
                    Value = x.Id.ToString(),
                    Text = x.Name
                }).ToListAsync();

                var studentVM1 = new StudentViewModel()
                {
                    Students = students1,
                    Groups = groups1
                };
                return View(studentVM1);
            }
            else
            {
                int groupId = int.Parse(group);

                var students = await _context.Students
                    .Include(s => s.Enrollments)
                    .ThenInclude(e => e.Group)
                    .Where(s => s.FullName.ToLower().Contains(searchString.ToLower()))
                    .Where(x => x.Enrollments.Any(e => e.GroupId == groupId))
                    .ToListAsync();

                var groups = await _context.Groups.Select(x => new SelectListItem
                {
                    Value = x.Id.ToString(),
                    Text = x.Name
                }).ToListAsync();

                var studentVM = new StudentViewModel()
                {
                    Students = students,
                    Groups = groups
                };

                return View(studentVM);
            }
        }
        // GET: Students/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Students == null)
            {
                return NotFound();
            }

            var student = await _context.Students
                .FirstOrDefaultAsync(m => m.Id == id);
            if (student == null)
            {
                return NotFound();
            }

            return View(student);
        }

        // GET: Students/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Students/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,FullName,Age")] Student student)
        {
            if (ModelState.IsValid)
            {
                _context.Add(student);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(student);
        }

        // GET: Students/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Students == null)
            {
                return NotFound();
            }

            var student = await _context.Students.FindAsync(id);
            if (student == null)
            {
                return NotFound();
            }
            return View(student);
        }

        // POST: Students/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,FullName,Age")] Student student)
        {
            if (id != student.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(student);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!StudentExists(student.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(student);
        }

        // GET: Students/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Students == null)
            {
                return NotFound();
            }

            var student = await _context.Students
                .FirstOrDefaultAsync(m => m.Id == id);
            if (student == null)
            {
                return NotFound();
            }

            return View(student);
        }

        // POST: Students/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Students == null)
            {
                return Problem("Entity set 'PdpDbContext.Students'  is null.");
            }
            var student = await _context.Students.FindAsync(id);
            if (student != null)
            {
                _context.Students.Remove(student);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool StudentExists(int id)
        {
            return (_context.Students?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

PDP Academy/lesson03/Controllers/SubjectsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using PDP_Academy.DAL;
using PDP_Academy.Models;

namespace PDP_Academy.Controllers
{
    public class SubjectsController : Controller
    {
        private readonly PdpDbContext _context;

        public SubjectsController(PdpDbContext context)
        {
            _context = context;
        }

        // GET: Subjects
        public async Task<IActionResult> Index(string sortOrder)
        {
            ViewData["CurrentSort"] = sortOrder;
            ViewData["TitleSort"] = sortOrder == "title_asc" ? "title_desc" : "title_asc";
            ViewData["DescriptionSort"] = sortOrder == "description_asc" ? "description_desc" : "description_asc";
            ViewData["PriceSort"] = sortOrder == "price_asc" ? "price-desc" : "price_asc";
            ViewData["NumberOfModulesSort"] = sortOrder == "numberOfModules_asc" ? "numberOfModules_desc" : "numberOfModules_asc";
            ViewData["TotalHoursSort"] = sortOrder == "totalHours_asc" ? "totalHours_desc" : "totalHours_asc";

            var subjects = _context.Subjects.AsQueryable();

            subjects = sortOrder switch
            {
                "title_asc" => subjects.OrderBy(x => x.Title),
                "title_desc" => subjects.OrderByDescending(x => x.Title),
                "description_asc" => subjects.OrderBy(x => x.Description),
                "description_desc" => subjects.OrderByDescending(x => x.Description),
                "price_asc"=>subjects.OrderBy(x => x.Price),
                "price_desc"=>subjects.OrderByDescending(x=>x.Price),
                "numberOfModules_asc"=>subjects.OrderBy(x=>x.NumberOfModules),
                "numberOfModules-desc"=>subjects.OrderByDescending(x=>x.NumberOfModules),
                "totalHours_asc"=>subjects.OrderBy(x=>x.TotalHours),
                "totalHours_desc"=>subjects.OrderByDescending(x=>x.TotalHours),
                _ => subjects.OrderBy(x => x.Id)
            };
            return View(subjects);
        }
        [HttpPost]
        public async Task<IActionResult> Index(string? searchString,string a)
        {
            if (string.IsNullOrEmpty(searchString))
            {
                return View(await _context.Subjects.ToListAsync());
            }

            var subjects = await _context.Subjects
                .Include(s => s.Assignments)
                .Include(s=>s.Courses)


                .Where(s => s.Title.ToLower().Contains(searchString.ToLower()))
                .ToListAsync();
            return View(subjects);
        }
        // GET: Subjects/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Subjects == null)
            {
                return NotFound();
            }

            var subject = await _context.Subjects
                .FirstOrDefaultAsync(m => m.Id == id);
            if (subject == null)
            {
                return NotFound();
            }

            return View(subject);
        }

        // GET: Subjects/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Subjects/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Title,Description,Price,NumberOfModules,TotalHours")] Subject subject)
        {
            if (ModelState.IsValid)
            {
                _context.Add(subject);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(subject);
        }

        // GET: Subjects/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Subjects == null)
            {
                return NotFound();
            }

            var subject = await _context.Subjects.FindAsync(id);
            if (subject == null)
            {
                return NotFound();
            }
            return View(subject);
        }

        // POST: Subjects/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Title,Description,Price,NumberOfModules,TotalHours")] Subject subject)
        {
            if (id != subject.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(subject);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!SubjectExists(subject.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(subject);
        }

        // GET: Subjects/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Subjects == null)
            {
                return NotFound();
            }

            var subject = await _context.Subjects
                .FirstOrDefaultAsync(m => m.Id == id);
            if (subject == null)
            {
                return NotFound();
            }

            return View(subject);
        }

        // POST: Subjects/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Subjects == null)
            {
                return Problem("Entity set 'PdpDbContext.Subjects'  is null.");
            }
            var subject = await _context.Subjects.FindAsync(id);
            if (subject != null)
            {
                _context.Subjects.Remove(subject);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool SubjectExists(int id)
        {
          return (_context.Subjects?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

PDP Academy/lesson03/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Lesson03</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Lesson03.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/lib/font-awesome/css/all.min.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                    PDP <i class="fa-solid fa-school"></i>
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Students" asp-action="Index">
                                Students <i class="fa-solid fa-graduation-cap"></i>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Teachers" asp-action="Index">
                                Teachers <i class="fa-solid fa-person-chalkboard"></i>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Subjects" asp-action="Index">
                                Subjects <i class="fa-solid fa-book-open"></i>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Assignments" asp-action="Index">
                                Assignments <i class="fa-solid fa-chalkboard-user"></i>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="CourseGroups" asp-action="Index">
                                Groups <i class="fa-solid fa-user-group"></i>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Enrollments" asp-action="Index">
                                Enrollments <i class="fa-regular fa-id-card"></i>
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Lesson03 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>