Book_Shop/EXAM/Models/Author.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace EXAM.Models
{
    public class Author
    {
        public int Id { get; set; }
        public string FullName { get; set; }
        public DateTime Brithday { get; set; } 
        public ICollection<Book> Books { get; set; }    
    }
}

Book_Shop/EXAM/Controllers/AuthorsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using EXAM.Data;
using EXAM.Models;

namespace EXAM.Controllers
{
    public class AuthorsController : Controller
    {
        private readonly BookShopDbContext _context;

        public AuthorsController(BookShopDbContext context)
        {
            _context = context;
        }

        [HttpPost]
        public async Task<IActionResult> Index(string? searchString, string a)
        {
            if (string.IsNullOrEmpty(searchString))
            {
                return View(await _context.Authors.ToListAsync());
            }

            var authors = await _context.Authors
                .Where(s => s.FullName.ToLower().Contains(searchString.ToLower()))
                .ToListAsync();

            return View(authors);
        }

        // GET: Authors
        public async Task<IActionResult> Index(string sortOrder)
        {
            ViewData["CurrentSort"] = sortOrder;
            ViewData["IdSort"] = sortOrder == "Id_asc" ? "Id_desc" : "Id_asc";
            ViewData["FullNameSort"] = sortOrder == "FullName_asc" ? "FullName_desc" : "FullName_asc";
            ViewData["BirhtdaySort"] = sortOrder == "Birhtday_asc" ? "Birhtday_asc" : "Birhtday_asc";

            var author = _context.Authors.AsQueryable();

            author = sortOrder switch
            {
                "Id_asc"=> author.OrderBy(x=>x.Id),
                "Id_desc"=>author.OrderByDescending(x=>x.Id),
                "FullName_asc" => author.OrderBy(x => x.FullName),
                "FullName_desc" => author.OrderByDescending(x => x.FullName),
                "Birhtday_asc" => author.OrderBy(x => x.Brithday),
                "Birhtday_desc" => author.OrderByDescending(x => x.Brithday),
                _ => author.OrderBy(x => x.Id)
            }; ;
            return View(author);
        }

        // GET: Authors/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Authors == null)
            {
                return NotFound();
            }

            var author = await _context.Authors
                .FirstOrDefaultAsync(m => m.Id == id);
            if (author == null)
            {
                return NotFound();
            }

            return View(author);
        }

        // GET: Authors/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Authors/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,FullName,Brithday")] Author author)
        {
            if (author!=null)
            {
                _context.Add(author);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(author);
        }

        // GET: Authors/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Authors == null)
            {
                return NotFound();
            }

            var author = await _context.Authors.FindAsync(id);
            if (author == null)
            {
                return NotFound();
            }
            return View(author);
        }

        // POST: Authors/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,FullName,Brithday")] Author author)
        {
            if (id != author.Id)
            {
                return NotFound();
            }

            if (author!=null)
            {
                try
                {
                    _context.Update(author);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AuthorExists(author.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(author);
        }

        // GET: Authors/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Authors == null)
            {
                return NotFound();
            }

            var author = await _context.Authors
                .FirstOrDefaultAsync(m => m.Id == id);
            if (author == null)
            {
                return NotFound();
            }

            return View(author);
        }

        // POST: Authors/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Authors == null)
            {
                return Problem("Entity set 'BookShopDbContext.Authors'  is null.");
            }
            var author = await _context.Authors.FindAsync(id);
            if (author != null)
            {
                _context.Authors.Remove(author);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool AuthorExists(int id)
        {
          return (_context.Authors?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

Book_Shop/EXAM/Views/Authors/Create.cshtml
@model EXAM.Models.Author

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>
    
<h4>Author</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="FullName" class="control-label"></label>
                <input asp-for="FullName" class="form-control" />
                <span asp-validation-for="FullName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Brithday" class="control-label"></label>
                <input asp-for="Brithday" class="form-control" />
                <span asp-validation-for="Brithday" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Book_Shop/EXAM/Views/Authors/Delete.cshtml
@model EXAM.Models.Author

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Author</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FullName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FullName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Brithday)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Brithday)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Book_Shop/EXAM/Views/Authors/Details.cshtml
@model EXAM.Models.Author

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Author</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FullName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FullName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Brithday)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Brithday)
        </dd>
    </dl>
</div>
<div>
    <a class="btn btn-outline-primary" asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a class="btn btn-outline-danger" asp-action="Delete" asp-route-id="@Model?.Id">Delete</a> |
    <a class="btn btn-outline-warning" asp-action="Index">Back to List</a>
</div>

Book_Shop/EXAM/Views/Authors/Edit.cshtml
@model EXAM.Models.Author

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Author</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="FullName" class="control-label"></label>
                <input asp-for="FullName" class="form-control" />
                <span asp-validation-for="FullName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Brithday" class="control-label"></label>
                <input asp-for="Brithday" class="form-control" />
                <span asp-validation-for="Brithday" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Book_Shop/EXAM/Views/Authors/Index.cshtml
@model IEnumerable<EXAM.Models.Author>

@{
    ViewData["Title"] = "Index";
}

<h1>Author</h1>

<form asp-controller="Authors" asp-action="Index">
    <p>
        Search name: <input type="text" name="SearchString" />
        <input type="submit" value="Search" />
    </p>
</form>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                <a class="text-dark" asp-route-sortorder="@ViewData["IdSort"]">
                    @Html.DisplayName("Id") <i class="fa fa-sort"></i>
                </a>
            </th>
            <th>
                <a class="text-dark" asp-route-sortorder="@ViewData["FullNameSort"]">
                    @Html.DisplayName("Full Name") <i class="fa fa-sort"></i>
                </a>
            </th>
            <th>
                <a class="text-dark" asp-route-sortorder="@ViewData["BirhtdaySort"]">
                    @Html.DisplayName("Birthday") <i class="fa fa-sort"></i>
                </a>
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                <a asp-action="Details" asp-route-id="@item.Id" >
                        @Html.DisplayFor(modelItem => item.Id)
                </a>
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FullName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Brithday)
            </td>
        </tr>
}
    </tbody>
</table>