PDP Academy/lesson03/Models/CourseGroup.cs
namespace PDP_Academy.Models
{
    public class CourseGroup
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public DateTime StartDate { get; set; }
        public DateTime? ExpectedFinishDate { get; set; }
        public DateTime? ActualFinishDate { get; set; }
        public int CurrentModule { get; set; }

        public int SubjectId { get; set; }
        public Subject Subject { get; set; }

        public int TeacherId { get; set; }
        public Teacher Teacher { get; set; }

        public virtual ICollection<Enrollment> Enrollments { get; set; }

        public CourseGroup()
        {
            Enrollments = new List<Enrollment>();
        }
    }
}

PDP Academy/lesson03/Controllers/CourseGroupsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PDP_Academy.DAL;
using PDP_Academy.Models;

namespace PDP_Academy.Controllers
{
    public class CourseGroupsController : Controller
    {
        private readonly PdpDbContext _context;

        public CourseGroupsController(PdpDbContext context)
        {
            _context = context;
        }

        // GET: CourseGroups
        public async Task<IActionResult> Index()
        {
            var pdpDbContext = _context.Groups.Include(c => c.Subject).Include(c => c.Teacher);
            return View(await pdpDbContext.ToListAsync());
        }
        [HttpPost]
        public async Task<IActionResult> Index(string searchString)
        {
            var courseGroups = _context.Groups.AsQueryable();
            if (string.IsNullOrEmpty(searchString))
            {
                courseGroups = courseGroups
                    .Include(cg => cg.Subject)
                    .Include(cg => cg.Teacher);
                return View(await courseGroups.ToListAsync());

            }
            courseGroups = courseGroups
                .Where(cg => cg.Name.ToLower().Contains(searchString.ToLower()))
                .Include(cg => cg.Subject)
                .Include(cg => cg.Teacher);
            return View(await courseGroups.ToListAsync());

        }
        // GET: CourseGroups/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Groups == null)
            {
                return NotFound();
            }

            var courseGroup = await _context.Groups
                .Include(c => c.Subject)
                .Include(c => c.Teacher)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (courseGroup == null)
            {
                return NotFound();
            }

            return View(courseGroup);
        }

        // GET: CourseGroups/Create
        public IActionResult Create()
        {
            ViewData["SubjectId"] = new SelectList(_context.Subjects, "Id", "Id");
            ViewData["TeacherId"] = new SelectList(_context.Teachers, "Id", "Id");
            return View();
        }

        // POST: CourseGroups/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,StartDate,ExpectedFinishDate,ActualFinishDate,SubjectId,TeacherId")] CourseGroup courseGroup)
        {
            if (ModelState.IsValid)
            {
                _context.Add(courseGroup);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["SubjectId"] = new SelectList(_context.Subjects, "Id", "Id", courseGroup.SubjectId);
            ViewData["TeacherId"] = new SelectList(_context.Teachers, "Id", "Id", courseGroup.TeacherId);
            return View(courseGroup);
        }

        // GET: CourseGroups/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Groups == null)
            {
                return NotFound();
            }

            var courseGroup = await _context.Groups.FindAsync(id);
            if (courseGroup == null)
            {
                return NotFound();
            }
            ViewData["SubjectId"] = new SelectList(_context.Subjects, "Id", "Id", courseGroup.SubjectId);
            ViewData["TeacherId"] = new SelectList(_context.Teachers, "Id", "Id", courseGroup.TeacherId);
            return View(courseGroup);
        }

        // POST: CourseGroups/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,StartDate,ExpectedFinishDate,ActualFinishDate,SubjectId,TeacherId")] CourseGroup courseGroup)
        {
            if (id != courseGroup.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(courseGroup);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CourseGroupExists(courseGroup.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["SubjectId"] = new SelectList(_context.Subjects, "Id", "Id", courseGroup.SubjectId);
            ViewData["TeacherId"] = new SelectList(_context.Teachers, "Id", "Id", courseGroup.TeacherId);
            return View(courseGroup);
        }

        // GET: CourseGroups/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Groups == null)
            {
                return NotFound();
            }

            var courseGroup = await _context.Groups
                .Include(c => c.Subject)
                .Include(c => c.Teacher)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (courseGroup == null)
            {
                return NotFound();
            }

            return View(courseGroup);
        }

        // POST: CourseGroups/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Groups == null)
            {
                return Problem("Entity set 'PdpDbContext.Groups'  is null.");
            }
            var courseGroup = await _context.Groups.FindAsync(id);
            if (courseGroup != null)
            {
                _context.Groups.Remove(courseGroup);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CourseGroupExists(int id)
        {
          return (_context.Groups?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

PDP Academy/lesson03/Views/CourseGroups/Create.cshtml
@model PDP_Academy.Models.CourseGroup

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>CourseGroup</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="StartDate" class="control-label"></label>
                <input asp-for="StartDate" class="form-control" />
                <span asp-validation-for="StartDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ExpectedFinishDate" class="control-label"></label>
                <input asp-for="ExpectedFinishDate" class="form-control" />
                <span asp-validation-for="ExpectedFinishDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ActualFinishDate" class="control-label"></label>
                <input asp-for="ActualFinishDate" class="form-control" />
                <span asp-validation-for="ActualFinishDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SubjectId" class="control-label"></label>
                <select asp-for="SubjectId" class ="form-control" asp-items="ViewBag.SubjectId"></select>
            </div>
            <div class="form-group">
                <label asp-for="TeacherId" class="control-label"></label>
                <select asp-for="TeacherId" class ="form-control" asp-items="ViewBag.TeacherId"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

PDP Academy/lesson03/Views/CourseGroups/Delete.cshtml
@model PDP_Academy.Models.CourseGroup

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>CourseGroup</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.StartDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.StartDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ExpectedFinishDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ExpectedFinishDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ActualFinishDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ActualFinishDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Subject)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Subject.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Teacher)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Teacher.Id)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

PDP Academy/lesson03/Views/CourseGroups/Details.cshtml
@model PDP_Academy.Models.CourseGroup

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>CourseGroup</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.StartDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.StartDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ExpectedFinishDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ExpectedFinishDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ActualFinishDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ActualFinishDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Subject)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Subject.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Teacher)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Teacher.Id)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

PDP Academy/lesson03/Views/CourseGroups/Edit.cshtml
@model PDP_Academy.Models.CourseGroup

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>CourseGroup</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="StartDate" class="control-label"></label>
                <input asp-for="StartDate" class="form-control" />
                <span asp-validation-for="StartDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ExpectedFinishDate" class="control-label"></label>
                <input asp-for="ExpectedFinishDate" class="form-control" />
                <span asp-validation-for="ExpectedFinishDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ActualFinishDate" class="control-label"></label>
                <input asp-for="ActualFinishDate" class="form-control" />
                <span asp-validation-for="ActualFinishDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SubjectId" class="control-label"></label>
                <select asp-for="SubjectId" class="form-control" asp-items="ViewBag.SubjectId"></select>
                <span asp-validation-for="SubjectId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TeacherId" class="control-label"></label>
                <select asp-for="TeacherId" class="form-control" asp-items="ViewBag.TeacherId"></select>
                <span asp-validation-for="TeacherId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

PDP Academy/lesson03/Views/CourseGroups/Index.cshtml
@model IEnumerable<PDP_Academy.Models.CourseGroup>

@{
    ViewData["Title"] = "Index";
}

<h1>Groups</h1>
<form asp-controller="CourseGroups" asp-action="Index">
    <p>
        <div class="input-group">
            <div class="input-group-prepend">
                <span class="input-group-text">
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="27" fill="currentColor" class="bi bi-search" viewBox="0 0 16 16">
                        <path d="M11.742 10.344a6.5 6.5 0 1 0-1.397 1.398h-.001c.03.04.062.078.098.115l3.85 3.85a1 1 0 0 0 1.415-1.414l-3.85-3.85a1.007 1.007 0 0 0-.115-.1zM12 6.5a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0z" />
                    </svg>
                </span>
            </div>
            <input type="text" class="form-control" placeholder="Search by name" name="SearchString" />
            <div class="input-group-append">
                <button class="btn btn-outline-success" type="submit">
                    <i class="fas fa-search"></i> Search
                </button>
            </div>
        </div>
    </p>
</form>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.StartDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ExpectedFinishDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ActualFinishDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Subject)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Teacher)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.StartDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ExpectedFinishDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ActualFinishDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Subject.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Teacher.Id)
            </td>
            <td>
                <a class="btn btn-outline-primary" asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a class="btn btn-outline-secondary" asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a class="btn btn-outline-danger" asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>